# Generated by Django 2.1.5 on 2020-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.TextField(max_length=1024)),
                ('name', models.CharField(max_length=160)),
                ('time_date', models.CharField(max_length=160)),
                ('face_ids', models.CharField(max_length=160)),
                ('image_link', models.CharField(max_length=160)),
            ],
        ),
    ]
