# Generated by Django 2.1.5 on 2020-05-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='alias',
            new_name='faceId',
        ),
    ]
