# Generated by Django 2.1.5 on 2020-05-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200512_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='faceId',
            new_name='face_ids',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='lecture_number',
        ),
    ]
